package de.instinct.api.shipyard.dto;

public enum ShipStat {
	
	MOVEMENT_SPEED,
	COST,
	COMMAND_POINTS_COST,
	WEAPON_DAMAGE,
	WEAPON_RANGE,
	WEAPON_FIRE_RATE,
	WEAPON_PROJECTILE_SPEED,
	DEFENSE_ARMOR,
	DEFENSE_SHIELD,
	DEFENSE_SHIELD_REGENERATION_SPEED

}
